version: 0
allowPullRequests: public
metadata:
  name: "Mozilla Release Services"
  description: "Mozilla Release Services"
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:


  - metadata:
      name: "0. Decision task (pull request)"
      description: "A task that detects changes and rebuilds application that needs to be rebuilt."
      owner: "{{ event.head.user.email }}"
      source: "https://github.com/mozilla/release-services/tree/master"
    routes:
      - index.project.releng.services.requests.pull-request.{{ event.head.sha }}
    scopes:
      - docker-worker:capability:privileged
      - queue:create-task:highest:aws-provisioner-v1/releng-svc*
      - queue:route:index.project.releng.services.requests.pull-request.*
      - queue:scheduler-id:taskcluster-github
      - secrets:get:repo:github.com/mozilla-releng/services:pull-request
    extra:
      github:
        env: true
        events:
          - pull_request.*
        excludeBranches:
          - production
          - staging
          - testing
    provisionerId: "aws-provisioner-v1"
    workerType: "releng-svc"
    priority: high
    payload:
      maxRunTime: 1800  # 30min
      image: "mozillareleng/services:base-61"
      features:
        taskclusterProxy: true
      capabilities:
        privileged: true
      command:
        - "/bin/bash"
        - "-l"
        - "-c"
        - "source /etc/nix/profile.sh && cd /tmp && wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 5  https://github.com/mozilla/release-services/archive/$GITHUB_HEAD_SHA.tar.gz && tar zxf $GITHUB_HEAD_SHA.tar.gz && cd release-services-$GITHUB_HEAD_SHA && env && rm -rf /home/app/.cache/nix && ./please tools decision-task"

  - metadata:
      name: "0. Decision task (master)"
      description: "A task that detects changes and rebuilds application that needs to be rebuilt."
      owner: "{{ event.head.user.email }}"
      source: "https://github.com/mozilla/release-services/tree/master"
    routes:
      - index.project.releng.services.requests.{{ event.base.repo.branch }}.by-timestamp.{{ timestamp }}
      - index.project.releng.services.requests.{{ event.base.repo.branch }}.by-revision.{{ event.head.sha }}
    scopes:
      - assume:hook-id:project-releng/services-master-*
      - hooks:modify-hook:project-releng/services-master-*
      - queue:create-task:highest:aws-provisioner-v1/releng-*
      - queue:scheduler-id:taskcluster-github
      - queue:route:index.project.releng.services.requests.{{ event.base.repo.branch }}.*
      - secrets:get:repo:github.com/mozilla-releng/services:branch:master
      - docker-worker:capability:privileged
    extra:
      github:
        env: true
        events:
          - push
        branches:
          - master
    provisionerId: "aws-provisioner-v1"
    workerType: "releng-svc"
    priority: high
    payload:
      maxRunTime: 1800  # 30min
      image: "mozillareleng/services:base-61"
      features:
        taskclusterProxy: true
      capabilities:
        privileged: true
      command:
        - "/bin/bash"
        - "-l"
        - "-c"
        - "source /etc/nix/profile.sh && cd /tmp && wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 5  https://github.com/mozilla/release-services/archive/$GITHUB_HEAD_SHA.tar.gz && tar zxf $GITHUB_HEAD_SHA.tar.gz && cd release-services-$GITHUB_HEAD_SHA && env && rm -rf /home/app/.cache/nix && ./please tools decision-task"

  - metadata:
      name: "0. Decision task (testing)"
      description: "A task that detects changes and rebuilds application that needs to be rebuilt."
      owner: "{{ event.head.user.email }}"
      source: "https://github.com/mozilla/release-services/tree/testing"
    routes:
      - index.project.releng.services.requests.{{ event.base.repo.branch }}.by-timestamp.{{ timestamp }}
      - index.project.releng.services.requests.{{ event.base.repo.branch }}.by-revision.{{ event.head.sha }}
    scopes:
      - assume:hook-id:project-releng/services-testing-*
      - hooks:modify-hook:project-releng/services-testing-*
      - queue:create-task:highest:aws-provisioner-v1/releng-*
      - queue:scheduler-id:taskcluster-github
      - queue:route:index.project.releng.services.requests.{{ event.base.repo.branch }}.*
      - secrets:get:repo:github.com/mozilla-releng/services:branch:testing
      - docker-worker:capability:privileged
      - notify:irc-channel:#release-services
      - notify:irc-channel:#ci
    extra:
      github:
        env: true
        events:
          - push
        branches:
          - testing
    provisionerId: "aws-provisioner-v1"
    workerType: "releng-svc"
    priority: high
    payload:
      maxRunTime: 1800  # 30min
      image: "mozillareleng/services:base-61"
      features:
        taskclusterProxy: true
      capabilities:
        privileged: true
      command:
        - "/bin/bash"
        - "-l"
        - "-c"
        - "source /etc/nix/profile.sh && cd /tmp && wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 5  https://github.com/mozilla/release-services/archive/$GITHUB_HEAD_SHA.tar.gz && tar zxf $GITHUB_HEAD_SHA.tar.gz && cd release-services-$GITHUB_HEAD_SHA && env && rm -rf /home/app/.cache/nix && ./please tools decision-task"

  - metadata:
      name: "0. Decision task (staging)"
      description: "A task that detects changes and rebuilds application that needs to be rebuilt."
      owner: "{{ event.head.user.email }}"
      source: "https://github.com/mozilla/release-services/tree/staging"
    routes:
      - index.project.releng.services.requests.{{ event.base.repo.branch }}.by-timestamp.{{ timestamp }}
      - index.project.releng.services.requests.{{ event.base.repo.branch }}.by-revision.{{ event.head.sha }}
    scopes:
      - assume:hook-id:project-releng/services-staging-*
      - hooks:modify-hook:project-releng/services-staging-*
      - queue:create-task:highest:aws-provisioner-v1/releng-*
      - queue:scheduler-id:taskcluster-github
      - queue:route:index.project.releng.services.requests.{{ event.base.repo.branch }}.*
      - secrets:get:repo:github.com/mozilla-releng/services:branch:staging
      - docker-worker:capability:privileged
      - notify:irc-channel:#release-services
      - notify:irc-channel:#ci
    extra:
      github:
        env: true
        events:
          - push
        branches:
          - staging
    provisionerId: "aws-provisioner-v1"
    workerType: "releng-svc"
    priority: high
    payload:
      maxRunTime: 1800  # 30min
      image: "mozillareleng/services:base-61"
      features:
        taskclusterProxy: true
      capabilities:
        privileged: true
      command:
        - "/bin/bash"
        - "-l"
        - "-c"
        - "source /etc/nix/profile.sh && cd /tmp && wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 5  https://github.com/mozilla/release-services/archive/$GITHUB_HEAD_SHA.tar.gz && tar zxf $GITHUB_HEAD_SHA.tar.gz && cd release-services-$GITHUB_HEAD_SHA && env && rm -rf /home/app/.cache/nix && ./please tools decision-task"

  - metadata:
      name: "0. Decision task (production)"
      description: "A task that detects changes and rebuilds application that needs to be rebuilt."
      owner: "{{ event.head.user.email }}"
      source: "https://github.com/mozilla/release-services/tree/production"
    routes:
      - index.project.releng.services.requests.{{ event.base.repo.branch }}.by-timestamp.{{ timestamp }}
      - index.project.releng.services.requests.{{ event.base.repo.branch }}.by-revision.{{ event.head.sha }}
    scopes:
      - assume:hook-id:project-releng/services-production-*
      - hooks:modify-hook:project-releng/services-production-*
      - queue:create-task:highest:aws-provisioner-v1/releng-*
      - queue:scheduler-id:taskcluster-github
      - queue:route:index.project.releng.services.requests.{{ event.base.repo.branch }}.*
      - secrets:get:repo:github.com/mozilla-releng/services:branch:production
      - docker-worker:capability:privileged
      - notify:irc-channel:#release-services
      - notify:irc-channel:#ci
    extra:
      github:
        env: true
        events:
          - push
        branches:
          - production
    provisionerId: "aws-provisioner-v1"
    workerType: "releng-svc"
    priority: high
    payload:
      maxRunTime: 1800  # 30min
      image: "mozillareleng/services:base-61"
      features:
        taskclusterProxy: true
      capabilities:
        privileged: true
      command:
        - "/bin/bash"
        - "-l"
        - "-c"
        - "source /etc/nix/profile.sh && cd /tmp && wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 5  https://github.com/mozilla/release-services/archive/$GITHUB_HEAD_SHA.tar.gz && tar zxf $GITHUB_HEAD_SHA.tar.gz && cd release-services-$GITHUB_HEAD_SHA && env && rm -rf /home/app/.cache/nix && ./please tools decision-task"
